### ISSUE TITLE
Running IntegrationTest Against FakeS3 Server

### ISSUE THREAD

**Issue by japauljr** [opt-tech/redshift-fake-driver#11]
When running the Integration test against fakeS3 and CI=true,  the unload and copy calls fail.  Please provide the correct settings in order to have the IntegrationTest work.

$ sbt -Dfake.awsS3Endpoint="http://localhost:9444/" test
[info] Loading global plugins from /.sbt\0.13\plugins
[info] Loading project definition from /redshift-fake-driver\project
[info] Set current project to redshift-fake-driver (in build file:/redshift-fake-driver/)
[info] DDLParserTest:
[info] - should sanitize Redshift specific DDL
[info] JsonpathsTest:
[info] - should read json document by index in jsonpaths
[info] UnloadCommandParserTest:
[info] - should parse minimal UNLOAD command
[info] - should parse Manifest
[info] - should parse delimiter
[info] - should parse addQuotes
[info] - should parse multiple options
[info] CopyCommandParserTest:
[info] - should parse minimal COPY command
[info] - should parse JSON format
[info] - should parse date format
[info] - should parse time format
[info] - should parse manifest
[info] - should parse emptyAsNull
[info] IntegrationTest:
[info] - should unload / copy via manifest *** FAILED ***
[info]   jp.ne.opt.redshiftfake.read.InvalidManifestException: invalid manifest :
[info]   at jp.ne.opt.redshiftfake.read.Manifest.<init>(Manifest.scala:17)
[info]   at jp.ne.opt.redshiftfake.read.Reader.read(Reader.scala:17)
[info]   at jp.ne.opt.redshiftfake.CopyInterceptor$class.executeCopy(Interceptor.scala:29)
[info]   at jp.ne.opt.redshiftfake.FakeStatement.executeCopy(FakeStatement.scala:21)
[info]   at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$switchExecute$1.apply(FakeStatement.scala:111)
[info]   at jp.ne.opt.redshiftfake.FakeStatement$$anonfun$switchExecute$1.apply(FakeStatement.scala:110)
[info]   at scala.Option.map(Option.scala:145)
[info]   at jp.ne.opt.redshiftfake.FakeStatement.switchExecute(FakeStatement.scala:110)
[info]   at jp.ne.opt.redshiftfake.FakeStatement.execute(FakeStatement.scala:70)
[info]   at jp.ne.opt.redshiftfake.IntegrationTest$$anonfun$1.apply(IntegrationTest.scala:37)
[info]   ...
[info] Run completed in 1 second, 470 milliseconds.
[info] Total number of tests run: 14
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 13, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         jp.ne.opt.redshiftfake.IntegrationTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed Sep 26, 2017 1:07:29 PM

**Comment by ocadaruma** [comment]
@japauljr I cannot reproduce the issue.
What version of fakes3 are you using ?
