### ISSUE TITLE
Parse failure when using with Spark Redshift

### ISSUE THREAD

**Issue by IvanAtanasov** [opt-tech/redshift-fake-driver#22]
Trying to make this work with https://github.com/databricks/spark-redshift but having problems. Got so far with it but now running into an error where the original query doesn't seem to be converted to postgres compliant SQL due to a parse error.

From debugging I can see that at CopyCommandParserScala:90 the parsing failed with an error: 

> \`http://localhost:8000/' expected but \`s' found

I'm guessing this is because its looking for the fake endpoint specified by the property but is in fact finding a path beginning with s3://. Unfortunately using the spark redshift plugin, there is no way of changing this.

Is there any way around this? It does say in the README.md 'you do not have to change S3 URL in your SQL (copy/unload)' so I thought it would work, or am I misunderstanding?

Thanks,
Ivan

**Comment by ocadaruma** [comment]
Thank you for reporting the issue.
I will check by this week.

**Comment by ocadaruma** [comment]
@IvanAtanasov I think that this if fixed by setting `fake.awsS3Scheme` java property to `s3://`.
