### ISSUE TITLE
PSQLException on connect with the latest versions

### ISSUE THREAD

**Issue by janosmeszaros** [opt-tech/redshift-fake-driver#40]
Hi,

I tired to use the lib to test my `unload` command locally using postgres and fake-s3 but I experienced some issues during connecting to postgres. With versions `1.0.9` and `1.0.8` during startup I got the following exception:
`Operation requires a scrollable ResultSet, but this ResultSet is FORWARD_ONLY`

After some investigation it turned out the it's thrown by `ResultSet.first()` method, [here](https://github.com/opt-tech/redshift-fake-driver/blob/9f79955b767440dbf1fd3363d48e193a4fbd7c88/src/main/java/jp/ne/opt/redshiftfake/views/SystemViews.java#L25). I checked postgres driver's code for the above method and it requires not to have `FORWARD_ONLY` result set.

The fix should be pretty straightforward, during creation of the preparedStatement, it's type should be defined either `ResultSet.TYPE_SCROLL_INSENSITIVE` or `ResultSet.TYPE_SCROLL_SENSITIVE`. Alternatively, `ResultSet.first()` could be replaced.

Thanks,
Janos

**Comment by ocadaruma** [comment]
Thank you for reporting.
I will fix.

**Comment by ocadaruma** [comment]
Thank you for your contribution : https://github.com/opt-tech/redshift-fake-driver/pull/41
I released fixed version 1.0.10 .
