### ISSUE TITLE
SystemViews.java checks for pg_tab_def but tries to create pg_table_def

### ISSUE THREAD

**Issue by whale2** [opt-tech/redshift-fake-driver#43]
Doesn't seem very consistent, unless I miss the point what is it for:
 
https://github.com/opt-tech/redshift-fake-driver/blob/master/src/main/java/jp/ne/opt/redshiftfake/views/SystemViews.java

CREATE VIEW pg_table_def (...)

SELECT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'pg_tab_def')

**Comment by frankfarrell** [comment]
Yes, you are right, it should be pg_table_def in both places
